/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import conexion.ConexionBD;
import datos.AutomovilRow;
import datos.MarcaRow;
import dialogs.AutomovilDialog;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crisantru
 */
public class AutomovilFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AutomovilFrame
     */
    public AutomovilFrame() {
        initComponents();
        this.cargarFiltroMarcas();
        this.cargarFiltroClases();
        this.cargarAutomoviles();
        sdf = new SimpleDateFormat("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        cmb_marca = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmb_clase = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datos = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        lbl_num = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();

        setTitle("Administrador de Automoviles");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por..."));

        jLabel5.setText("Marca");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        cmb_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel2.setText("Clase");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(cmb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_clase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cmb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmb_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_buscar)
                .addGap(47, 47, 47))
        );

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_datos);

        jToolBar1.setRollover(true);

        jLabel1.setText("Registros: ");
        jToolBar1.add(jLabel1);

        lbl_num.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lbl_num.setText("0");
        jToolBar1.add(lbl_num);

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit.png"))); // NOI18N
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_borrar)))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_editar)
                    .addComponent(btn_agregar)
                    .addComponent(btn_borrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        new AutomovilDialog(null, true, true, new AutomovilRow());
        this.cargarAutomoviles();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
         int indice = this.tbl_datos.getSelectedRow();
        
        if(indice >= 0){
            AutomovilRow ar = this.listaAutomoviles.get(indice);
            System.out.println("indice: " + indice);
            new AutomovilDialog(null, true, false, ar);
            this.cargarAutomoviles();
        }else{
            JOptionPane.showMessageDialog(this, "Debes seleccionar un registro", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        int indice = this.tbl_datos.getSelectedRow();
        
        if(indice >= 0){
            
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar este registro?");
            
            if(respuesta == 0){
                AutomovilRow ar = this.listaAutomoviles.get(indice);
                String query = String.format("DELETE FROM automovil WHERE nomotor = %s", ar.getMotor());
                System.out.println(query);
                
                ConexionBD conn = null;
        
                try{
                    conn = new ConexionBD(host, puerto, bd, usu, pas);
                    int filas = conn.update(query).getUpdateCount();
                    JOptionPane.showMessageDialog(this, "Filas Afectadas" + filas, "Resultado", JOptionPane.INFORMATION_MESSAGE);
                    this.cargarAutomoviles();
                }catch(Exception ex){
                    ex.printStackTrace();
                }finally{
                    if(conn != null){
                        conn.close();
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debes seleccionar un registro", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        filtroMarca = null;    
        
        if(this.cmb_marca.getSelectedItem() != null ){
            filtroMarca = this.cmb_marca.getSelectedItem().toString();
            System.out.println("btn_buscar: " + filtroMarca);
        }
        
        if(this.cmb_clase.getSelectedItem() != null){
            filtroClase = this.cmb_clase.getSelectedItem().toString();
            System.out.println("btn_buscar: " + filtroMarca);         
        }
        
        this.cargarAutomoviles();
    }//GEN-LAST:event_btn_buscarActionPerformed
    
    private void cargarAutomoviles(){
        listaAutomoviles = new ArrayList<AutomovilRow>();
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], COLUMNAS);
        
        
        ConexionBD conn = null;
        
        try{
            
            conn = new ConexionBD(host, puerto , bd, usu, pas);
            String filtro="";
            
             if(filtroMarca != null && filtroMarca != "NO seleccionado"){
                
                filtro = String.format("WHERE m.nombre LIKE '%s'", filtroMarca);
                System.out.println("filtro: " + filtro);
            }
             
            if(filtroClase!= null && filtroClase != "NO seleccionado"){
                
                filtro = String.format("WHERE c.nombre LIKE '%s'", filtroClase);
                System.out.println("filtro: " + filtro);
            }
            
            String query = "select a.nomotor, a.modelo, a.anio, a.idmarca, m.nombre as marca,"
                    + " a.fechaensamble, a.precioventa, a.idclase,"
                    + " c.nombre as clase from automovil a "
                    + "inner join marca m on m.idmarca = a.idmarca "
                    + "inner join clase c on c.idclase = a.idclase\n" + filtro;
            System.out.println(query);
            ResultSet rs = conn.query(query).getResultSet();
            
            if(rs != null){
                while(rs.next()){
                    //-------------RELLENAR LISTA AutomovilROW------
                    AutomovilRow ar = new AutomovilRow();
                    ar.setMotor(rs.getInt("nomotor"));
                    ar.setModelo(rs.getString("modelo"));
                    ar.setAnio(rs.getString("anio"));
                    ar.setIdMarca(rs.getInt("idmarca"));
                    ar.setMarca(rs.getString("marca"));
                    ar.setFechaensamblaje(rs.getString("fechaensamble"));
                    ar.setPrecioventa(rs.getFloat("precioventa"));
                    ar.setIdClase(rs.getInt("idclase"));
                    ar.setClase(rs.getString("clase"));
                    listaAutomoviles.add(ar);
                    
                    // ----------------RELLENAR TABLE ------------------
                    Object fila[] = new Object[6];
                    fila[0] = rs.getString("modelo");
                    fila[1] = rs.getString("anio");
                    fila[2] = rs.getString("marca");
                    fila[3] = rs.getString("fechaensamble");
                    fila[4] = rs.getFloat("precioventa");
                    fila[5] = rs.getString("clase");
                    model.addRow(fila);
                }
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            if(conn != null){
                conn.close();
            }
        }
        
        this.tbl_datos.setModel(model);
        this.lbl_num.setText(""+ this.listaAutomoviles.size());
    }
    
    private void cargarFiltroMarcas(){
        ConexionBD conn = null;
        this.cmb_marca.removeAllItems();
        this.cmb_marca.addItem("NO seleccionado");
        
        try{
            conn = new ConexionBD(host, puerto , bd, usu, pas);
            String query = "SELECT nombre FROM marca";
            ResultSet rs = conn.query(query).getResultSet();
            if(rs != null){
                while(rs.next()){
                    String nombre = rs.getString("nombre");
                    this.cmb_marca.addItem(nombre);
                }
            }

        }catch(Exception ex){
            ex.printStackTrace();
        }finally{
            if(conn != null){
                conn.close();
            }
        }
        
    }
    
    private void cargarFiltroClases(){
        ConexionBD conn = null;
        this.cmb_clase.removeAllItems();
        this.cmb_clase.addItem("NO seleccionado");
        
        try{
            conn = new ConexionBD(host, puerto , bd, usu, pas);
            String query = "SELECT nombre FROM clase";
            ResultSet rs = conn.query(query).getResultSet();
            if(rs != null){
                while(rs.next()){
                    String nombre = rs.getString("nombre");
                    this.cmb_clase.addItem(nombre);
                }
            }

        }catch(Exception ex){
            ex.printStackTrace();
        }finally{
            if(conn != null){
                conn.close();
            }
        }
        
    }
    
    private SimpleDateFormat sdf;
    private String filtroMarca;
    private String filtroClase;
    private String[] COLUMNAS = {"Modelo", "Año", "Marca", "Fecha Ensamblaje", "Precio", "Clase"};
    private List<AutomovilRow> listaAutomoviles;
    
    private String host = "localhost";
    private String usu = "root";
    private String pas = "Nocturnal2802";
    private String bd = "agencia";
    private Integer puerto = 3306;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JComboBox<String> cmb_clase;
    private javax.swing.JComboBox<String> cmb_marca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_num;
    private javax.swing.JTable tbl_datos;
    // End of variables declaration//GEN-END:variables
}
