/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import conexion.ConexionBD;
import datos.ClienteRow;
import datos.MarcaRow;
import dialogs.ClienteDialog;
import dialogs.MarcaDialog;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crisantru
 */
public class ClientesFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientesFrame
     */
    public ClientesFrame() {
        initComponents();
        sdf = new SimpleDateFormat("yyyy-MM-dd");
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        jhc_fecha = new com.toedter.calendar.JDateChooser();
        btn_buscarC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_agregarC = new javax.swing.JButton();
        btn_editarC = new javax.swing.JButton();
        btn_eliminarC = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        lbl_num = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Administrador de Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda Clientes"));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Fecha nac.");

        btn_buscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search.png"))); // NOI18N
        btn_buscarC.setText("Buscar");
        btn_buscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nombre)
                    .addComponent(jhc_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(txt_apellidos))
                .addGap(30, 30, 30)
                .addComponent(btn_buscarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_buscarC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jhc_fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_datos);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btn_agregarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btn_agregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarCActionPerformed(evt);
            }
        });

        btn_editarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit.png"))); // NOI18N
        btn_editarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarCActionPerformed(evt);
            }
        });

        btn_eliminarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btn_eliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarCActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jLabel4.setText("N° Registros");
        jToolBar1.add(jLabel4);

        lbl_num.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lbl_num.setText("0");
        jToolBar1.add(lbl_num);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminarC)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregarC)
                            .addComponent(btn_editarC)
                            .addComponent(btn_eliminarC))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarCActionPerformed
        new ClienteDialog (null, true, true, new ClienteRow());
        
        this.cargarClientes();
        
    }//GEN-LAST:event_btn_agregarCActionPerformed

    private void btn_buscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarCActionPerformed
        filtroNombreC = null;
        filtroApellidoC = null;
        filtroFechaC = null;
        java.util.Date fecha = this.jhc_fecha.getDate();
        
        
        
        
        
        if(this.txt_nombre.getText() != null && !this.txt_nombre.getText().isEmpty()){    //busca por nombre
            filtroNombreC = this.txt_nombre.getText();
            System.out.println("btn_buscar: " + filtroNombreC);
        }
        
        if(this.txt_apellidos.getText() != null && !this.txt_apellidos.getText().isEmpty()){    //busca por apellido
            filtroApellidoC = this.txt_apellidos.getText();
            System.out.println("btn_buscar: " + filtroApellidoC);
        }
        
        if(fecha != null ){    //busca por fecha
            filtroFechaC = sdf.format(fecha);
            System.out.println("btn_buscar: " + filtroFechaC);
        }
            
        this.cargarClientes();
        
        
    }//GEN-LAST:event_btn_buscarCActionPerformed

    private void btn_editarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarCActionPerformed
        int indice = this.tbl_datos.getSelectedRow();
        
        if(indice >= 0){
            ClienteRow cr = this.listaClientes.get(indice);
            new ClienteDialog(null, true, false, cr);
            this.cargarClientes();
        }else{
            JOptionPane.showMessageDialog(this, "Debes seleccionar un registro", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_editarCActionPerformed

    private void btn_eliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarCActionPerformed
        int indice = this.tbl_datos.getSelectedRow();
        
        if(indice >= 0){
            
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar este registro?");
            
            if(respuesta == 0){
                ClienteRow cr = this.listaClientes.get(indice);
                String query = String.format("DELETE FROM cliente WHERE idcliente = %s", cr.getIdcliente());
                
                ConexionBD conn = null;
        
                try{
                    conn = new ConexionBD(host, puerto, bd, usu, pas);
                    int filas = conn.update(query).getUpdateCount();
                    JOptionPane.showMessageDialog(this, "Filas Afectadas" + filas, "Resultado", JOptionPane.INFORMATION_MESSAGE);
                    this.cargarClientes();
                }catch(Exception ex){
                    ex.printStackTrace();
                }finally{
                    if(conn != null){
                        conn.close();
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debes seleccionar un registro", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_eliminarCActionPerformed

    private void cargarClientes(){
        listaClientes = new ArrayList<ClienteRow>();
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], COLUMNAS);
        
 
        ConexionBD conn = null;
        
        try{
            conn = new ConexionBD(host, puerto , bd, usu, pas);
            String filtro = "";
            
            if(filtroNombreC != null){
                
                filtro = String.format("WHERE nombres LIKE '%s'", filtroNombreC);
                System.out.println("filtro: " + filtro);
            }
            
            
            if(filtroApellidoC != null){
                
                filtro += String.format("WHERE apellidos LIKE '%s'", filtroApellidoC);
                System.out.println("filtro: " + filtro);
                

            }
            
            
            if(filtroNombreC == null){
                if(filtroApellidoC == null){
                    if(filtroFechaC != null){
                        filtro = String.format("WHERE fechanacimiento LIKE  '%s'",filtroFechaC);
                        System.out.println("filtro: " + filtro);
                    }
                }
            }
            
            String query = "SELECT idcliente,nombres,apellidos,fechanacimiento FROM cliente\n" + filtro;
            System.out.println(query);
            ResultSet rs = conn.query(query).getResultSet();
            
            if(rs != null){
                while(rs.next()){
                    //-------------AGREGAR A LISTA DE CLIENTES------
                    ClienteRow cr = new ClienteRow();
                    cr.setIdcliente(rs.getInt("idcliente"));
                    cr.setNombre(rs.getString("nombres"));
                    cr.setApellidos(rs.getString("apellidos"));
                    cr.setFecha(rs.getString("fechanacimiento"));
                    listaClientes.add(cr);
                    
                    // ----------------RELLENAR TABLA ------------------
                    Object row[] = new Object[3];
                    row[0] = rs.getString("nombres");
                    row[1] = rs.getString("apellidos");
                    row[2] = rs.getString("fechanacimiento");
                    model.addRow(row);
                }
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }finally{
            if(conn!=null){
                conn.close();
            }
        }
        this.tbl_datos.setModel(model);
        this.lbl_num.setText(""+ this.listaClientes.size());
    }
    
    private String filtroNombreC;
    private String filtroApellidoC;
    private String filtroFechaC;
    
    private SimpleDateFormat sdf;
    
    private String[] COLUMNAS = {"Nombre", "Apellidos", "Fecha Nacimiento"};
    private List<ClienteRow> listaClientes;
    
    private String host = "localhost";
    private String usu = "root";
    private String pas = "Nocturnal2802";
    private String bd = "agencia";
    private Integer puerto = 3306;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarC;
    private javax.swing.JButton btn_buscarC;
    private javax.swing.JButton btn_editarC;
    private javax.swing.JButton btn_eliminarC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private com.toedter.calendar.JDateChooser jhc_fecha;
    private javax.swing.JLabel lbl_num;
    private javax.swing.JTable tbl_datos;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
