
import conexion.ConexionBD;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author crisantru
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_host = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_consulta = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_datos = new javax.swing.JTable();
        spn_puerto = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txt_basedatos = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btn_consultar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_dialogo = new javax.swing.JButton();
        pass_contrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hostname");

        jLabel2.setText("Puerto");

        jLabel3.setText("Usuario");

        jLabel4.setText("Contraseña");

        txa_consulta.setColumns(20);
        txa_consulta.setRows(5);
        jScrollPane1.setViewportView(txa_consulta);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_datos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );

        spn_puerto.setModel(new javax.swing.SpinnerNumberModel(3306, null, null, 1));

        jLabel5.setText("Base Datos");

        jToolBar1.setRollover(true);

        btn_consultar.setText("Ejecutar Consulta");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_consultar);

        btn_limpiar.setText("Limpiar Consulta");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_limpiar);

        jButton1.setText("Nueva Clase");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        btn_dialogo.setText("Mostar Dialog");
        btn_dialogo.setFocusable(false);
        btn_dialogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dialogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dialogoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dialogo);

        pass_contrasena.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txt_host, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spn_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_basedatos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txt_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spn_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_basedatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txa_consulta.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        if(validarDatosConexion()){
            String host = this.txt_host.getText();
            String user = this.txt_usuario.getText();
            String pass = this.pass_contrasena.getText();
            String bd = this.txt_basedatos.getText();
            Integer puerto = Integer.parseInt(this.spn_puerto.getValue().toString());
            
            DefaultTableModel model = new DefaultTableModel();
            ConexionBD conn = null;
            try{
                conn = new ConexionBD(host, puerto, bd, user, pass);
                String consulta = this.txa_consulta.getText();
                if(soloConsulta(consulta)){
                    ResultSet rs = conn.query(consulta).getResultSet();
                    int colums = 0;
                    if(rs != null){
                        //--------------------LEER NOMBRE DE COLUMNAS---------------------
                        colums = rs.getMetaData().getColumnCount();
                        String NOMBRE_COLUMNAS[] = new String[colums];
                        for(int i = 0; i < colums; i++){
                            NOMBRE_COLUMNAS[i] = rs.getMetaData().getColumnName(i + 1);
                        }
                        //--------------------CREAR MODELO TABLA------------------------
                        model = new DefaultTableModel(new Object[0][0], NOMBRE_COLUMNAS);
                        //--------------------LEER DATOS DE LA CONSULTA-----------------
                        while(rs.next()){
                            Object fila[] = new Object[colums];
                            for(int i = 0; i < colums; i++){
                                fila[i] = rs.getString(i + 1);
                            }
                            model.addRow(fila);
                        }
                    }
                }else{
                    int filasafectadas = conn.update(consulta).getUpdateCount();
                    JOptionPane.showMessageDialog(this, filasafectadas+"fila(s) afectada(s)", "comando ejecutado", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this,ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
            }finally{
                if(conn!= null){
                        conn.close();
                }

            }
            this.tbl_datos.setModel(model);
        }
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AltaClase().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_dialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dialogoActionPerformed
        new AltaMarcas(this,true).setVisible(true);
    }//GEN-LAST:event_btn_dialogoActionPerformed

    public boolean soloConsulta(String consulta){
        String comandosActualizacion [] = {"INSERT", "UPDATE", "DELETE", "CREATE", "ALTER", "DROP", "TRUNCATE"};
        if(consulta != null){
            consulta = consulta.toUpperCase();
            for(String com : comandosActualizacion){
                if(consulta.contains(com)){
                    return false;
                }
            }
        }
        return true;
    }
    
    public boolean validarDatosConexion(){
        if(this.txt_host == null || txt_host.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo hostname es requerido",
                    "campo vacio", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if(this.txt_basedatos == null || txt_basedatos.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo SID es requerido",
                    "campo vacio", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if(this.txt_usuario == null || txt_usuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo Usuario es requerido", 
                    "campo vacio", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if(this.pass_contrasena == null || pass_contrasena.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo Contraseñaes requerido", 
                    "campo vacio", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if(this.spn_puerto == null || Integer.parseInt(spn_puerto.getValue().toString()) <= 0){
            JOptionPane.showMessageDialog(this, "El campo puerto es requerido y "
                    + "debe ser mayor a cero", "Campo vacio o incorrecto",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_dialogo;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPasswordField pass_contrasena;
    private javax.swing.JSpinner spn_puerto;
    private javax.swing.JTable tbl_datos;
    private javax.swing.JTextArea txa_consulta;
    private javax.swing.JTextField txt_basedatos;
    private javax.swing.JTextField txt_host;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
